### ISSUE TITLE
Collapsed Bullets not obvious in dark mode

### ISSUE THREAD

**Issue by DimaBert** [rcvd/rs2-testing#1]
Collapsed Bullets are difficult to distinguish from normal bullets in dark mode compared to light mode

![image](https://github.com/rcvd/rs2-testing/assets/94290928/7eb23452-489d-4419-b318-ce0b6aaf80ed)
![image](https://github.com/rcvd/rs2-testing/assets/94290928/f01bc787-6263-4f76-bc54-a0f76961df1a)

**Comment by rcvd** [comment]
Do you prefer the ring about a collapsed bullet? Or do you just recommend making the un-collapsed bullet a tick darker in dark-mode?

**Comment by DimaBert** [comment]
I think the ring would be better and less confusing for both dark and light themes
