### ISSUE TITLE
Arrow doesn't have highlighted background

### ISSUE THREAD

**Issue by harpreetchima** [rcvd/rs2-testing#2]
Maybe this was a design choice, but the arrows on the left side of the blocks don't have a highlighted background like the rest of the blocks.

![image](https://github.com/rcvd/rs2-testing/assets/46920506/0af93275-69e3-4e5b-afa2-c74bd88e8a41)

**Comment by rcvd** [comment]
Good catch - I introduced this lately for the search component to make overlaying the side border more visually appealing:

<img width="910" alt="Screenshot 2024-06-03 at 07 07 16" src="https://github.com/rcvd/rs2-testing/assets/12938875/7ea5213c-0856-49d4-aff1-7e9d0dc2e6b2">

But maybe I should put the caret back inside the box and make the background transparent again...
